/* eslint-disable no-control-regex */
export const REGEX_PATTERNS = {
  EMAIL: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
  EMAIL_STRICT:
    /^(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])$/i,
  PHONE_US: /^(\+1|1)?[-.\s]?\(?([0-9]{3})\)?[-.\s]?([0-9]{3})[-.\s]?([0-9]{4})$/,
  PHONE_US_STRICT: /^(\+1\s?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$/,
  PHONE_DIGITS_ONLY: /^\d{10}$/,
  ZIP_CODE: /^\d{5}$/,
  ZIP_CODE_PLUS_4: /^\d{5}(-\d{4})?$/,
  STREET_ADDRESS: /^[a-zA-Z0-9\s,.'#-]+$/,
  PO_BOX: /^P\.?\s?O\.?\s?Box\s+\d+$/i,
  NAME: /^[a-zA-Z\s'-]{2,50}$/,
  FIRST_NAME: /^[a-zA-Z][a-zA-Z\s'-]{1,49}$/,
  LAST_NAME: /^[a-zA-Z][a-zA-Z\s'-]{1,49}$/,
  FULL_NAME: /^[a-zA-Z][a-zA-Z\s'-]{2,}$/,
  POSITIVE_INTEGER: /^\d+$/,
  POSITIVE_NUMBER: /^\d+(\.\d+)?$/,
  INTEGER: /^-?\d+$/,
  DECIMAL: /^-?\d+(\.\d{1,2})?$/,
  CURRENCY_USD: /^\$?\d{1,3}(,?\d{3})*(\.\d{2})?$/,
  AMOUNT: /^\d+(\.\d{1,2})?$/,
  ALPHANUMERIC: /^[a-zA-Z0-9]+$/,
  ALPHANUMERIC_SPACES: /^[a-zA-Z0-9\s]+$/,
  USERNAME: /^[a-zA-Z0-9_-]{3,20}$/,
  PASSWORD_WEAK: /^.{6,}$/,
  PASSWORD_MEDIUM: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$/,
  PASSWORD_STRONG: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/,
  DATE_US: /^(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])\/\d{4}$/,
  DATE_US_SHORT: /^(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])\/\d{2}$/,
  URL: /^(https?:\/\/)?([\da-z.-]+)\.([a-z.]{2,6})([/\w .-]*)*\/?$/,
  URL_STRICT: /^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_+.~#?&//=]*)$/,
  SSN: /^\d{3}-?\d{2}-?\d{4}$/,
  SSN_STRICT: /^(?!000|666|9\d{2})\d{3}-?(?!00)\d{2}-?(?!0000)\d{4}$/,
  CREDIT_CARD: /^\d{4}[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4}$/,
  CVV: /^\d{3,4}$/,
  TIME_12HR: /^(0?[1-9]|1[0-2]):[0-5][0-9]\s?(AM|PM)$/i,
  TIME_24HR: /^([01]?[0-9]|2[0-3]):[0-5][0-9]$/,
  HEX_COLOR: /^#?([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$/,
  IPV4: /^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/,
  IMAGE_FILE: /\.(jpg|jpeg|png|gif|bmp|webp|svg)$/i,
  DOCUMENT_FILE: /\.(pdf|doc|docx|txt|xls|xlsx)$/i,
  EIN: /^\d{2}-?\d{7}$/,
  STATE_ABBR: /^(A[LKSZR]|C[AOT]|D[EC]|F[LM]|G[AU]|HI|I[ADLN]|K[SY]|LA|M[ADEHINOPST]|N[CDEHJMVY]|O[HKR]|P[ARW]|RI|S[CD]|T[NX]|UT|V[AIT]|W[AIVY])$/,
}

export const ERROR_MESSAGES = {
  EMAIL: "Please enter a valid email address",
  PHONE: "Please enter a valid US phone number (e.g., (555) 123-4567)",
  ZIP_CODE: "Please enter a valid 5-digit ZIP code",
  ZIP_CODE_PLUS_4: "Please enter a valid ZIP code (e.g., 12345 or 12345-6789)",
  NAME: "Please enter a valid name (letters, spaces, hyphens, and apostrophes only)",
  REQUIRED: "This field is required",
  INVALID_FORMAT: "Invalid format",
  PASSWORD_WEAK: "Password must be at least 6 characters",
  PASSWORD_MEDIUM: "Password must contain uppercase, lowercase, and number",
  PASSWORD_STRONG: "Password must contain uppercase, lowercase, number, and special character",
  SSN: "Please enter a valid Social Security Number",
  CREDIT_CARD: "Please enter a valid credit card number",
  CVV: "Please enter a valid CVV (3-4 digits)",
  DATE: "Please enter a valid date (MM/DD/YYYY)",
  POSITIVE_NUMBER: "Please enter a positive number",
  CURRENCY: "Please enter a valid amount",
}

export type RegexPatternKey = keyof typeof REGEX_PATTERNS

